# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from proto import kensho_pb2 as proto_dot_kensho__pb2


class KenshoStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.DoKensho = channel.unary_stream(
        '/kensho.Kensho/DoKensho',
        request_serializer=proto_dot_kensho__pb2.KenshoRequest.SerializeToString,
        response_deserializer=proto_dot_kensho__pb2.KenshoResponse.FromString,
        )
    self.DoAdminKensho = channel.unary_unary(
        '/kensho.Kensho/DoAdminKensho',
        request_serializer=proto_dot_kensho__pb2.KenshoAdminRequest.SerializeToString,
        response_deserializer=proto_dot_kensho__pb2.KenshoAdminResponse.FromString,
        )


class KenshoServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def DoKensho(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DoAdminKensho(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_KenshoServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'DoKensho': grpc.unary_stream_rpc_method_handler(
          servicer.DoKensho,
          request_deserializer=proto_dot_kensho__pb2.KenshoRequest.FromString,
          response_serializer=proto_dot_kensho__pb2.KenshoResponse.SerializeToString,
      ),
      'DoAdminKensho': grpc.unary_unary_rpc_method_handler(
          servicer.DoAdminKensho,
          request_deserializer=proto_dot_kensho__pb2.KenshoAdminRequest.FromString,
          response_serializer=proto_dot_kensho__pb2.KenshoAdminResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'kensho.Kensho', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
