# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from user_service_client.proto import authentication_pb2 as user__service__client_dot_proto_dot_authentication__pb2


class AuthenticationStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Login = channel.unary_unary(
        '/authentication.Authentication/Login',
        request_serializer=user__service__client_dot_proto_dot_authentication__pb2.LoginRequest.SerializeToString,
        response_deserializer=user__service__client_dot_proto_dot_authentication__pb2.LoginResponse.FromString,
        )
    self.SignUp = channel.unary_unary(
        '/authentication.Authentication/SignUp',
        request_serializer=user__service__client_dot_proto_dot_authentication__pb2.SignUpRequest.SerializeToString,
        response_deserializer=user__service__client_dot_proto_dot_authentication__pb2.SignUpResponse.FromString,
        )


class AuthenticationServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Login(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SignUp(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AuthenticationServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Login': grpc.unary_unary_rpc_method_handler(
          servicer.Login,
          request_deserializer=user__service__client_dot_proto_dot_authentication__pb2.LoginRequest.FromString,
          response_serializer=user__service__client_dot_proto_dot_authentication__pb2.LoginResponse.SerializeToString,
      ),
      'SignUp': grpc.unary_unary_rpc_method_handler(
          servicer.SignUp,
          request_deserializer=user__service__client_dot_proto_dot_authentication__pb2.SignUpRequest.FromString,
          response_serializer=user__service__client_dot_proto_dot_authentication__pb2.SignUpResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'authentication.Authentication', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
